#version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    hostname: mongodb
    volumes:
      - ${MONGO_DATA_PATH}:/data/db/
      - ${MONGO_LOG_PATH}:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongodb_network

networks:
  mongodb_network:
    driver: bridge
    name: mongo-network
